### ISSUE TITLE
[CS+IT][Team007] [Codeforces Clone]

### ISSUE THREAD

**Issue by Sidharth-Singh10** [IIITLucknowSWEngg/Assignment#1]
Description:
Codeforces is a competitive programming platform where users solve algorithmic problems and participate in contests. It features a vast collection of problems, user rankings, and regular contests, including rated and unrated rounds. Codeforces fosters a global community of programmers, providing a space for skill development and coding practice.
Team Members:
Sidharth Kumar Singh (CS43)
RishiRaj Mukherjee (IT30)
Yatin Sharma (IT48)
Ayush Yadav (IT49)
Maneesh  Shukla (IT40)
Yuwansh Bansal (CS05)

**Comment by VinayaSathyanarayana** [comment]
Approved
