### ISSUE TITLE
[CSAI+CSB][Team009] [SPOTIFY Clone]

### ISSUE THREAD

**Issue by Prudhvi-232** [IIITLucknowSWEngg/Assignment#10]
Spotify is a leading music streaming service that provides users with access to a vast library of songs, albums, podcasts, and playlists. It offers a user-friendly platform where individuals can discover, listen to, and share their favorite music across various devices. With personalized recommendations, curated playlists, and a wide range of genres, Spotify caters to different musical tastes and preferences, making it a go-to destination for music lovers worldwide.

TEAM MEMBERS:

1. Priyanshu Shah  LCI2023027
2. Ananya Kuchhal  LCB2023044
3. Kaithey Hanika Vasu  LCB2023015
4. Jaswanth Prudhvi  LCI2023002
5. Vedamsh  LCI2023004
6. Vaidehi Joshi  LCB2023014
7. Arjun Kunwar  LCI2023026

**Comment by VinayaSathyanarayana** [comment]
Approved
