### ISSUE TITLE
[CS-IT][Team - 006] [Pinterest Clone]

### ISSUE THREAD

**Issue by Hemasri05** [IIITLucknowSWEngg/Assignment#11]
Pinterest is a visually-driven social media platform that allows users to discover, save, and share ideas through images and videos known as "pins." Users can organize these pins into themed collections called "boards," making it easy to explore and categorize various interests, from fashion to home decor.

TEAM MEMBERS:-
Sankaramaddi Yamini - CS, LCS2023031
Mula Yuva Hemasri - CS, LCS2023007
V Akshaya - CS, LCS2023011
Pappala Sai Sri Chandana - CS, LCS2023037
Kureti Nidhish - CS, LCS2023016
Bada Moksha Sai Reddy - IT, LIT2023053
Thatikonda Venkata Sai Tejesh - IT, LIT2023010
Chagapuram Srivastav - IT, LIT2023037

**Comment by VinayaSathyanarayana** [comment]
Approved
