### ISSUE TITLE
[CS-IT][Team - 014] [PhonePe Clone]

### ISSUE THREAD

**Issue by SiddharthPaladi** [IIITLucknowSWEngg/Assignment#12]
PhonePe  is a digital payment platform that allows users to make secure UPI-based transactions, pay bills, and transfer money directly from their bank accounts. It offers a seamless experience for recharges, utility payments, and merchant transactions, all within a user-friendly mobile app.

TEAM MEMBERS:-

Tadikonda Purna Naga Phaneendra  LIT2023026
Kukkudapu Srinidhi   LCS2023027
Kalyan Chilamkuri   LCS2023030 
Siddharth Paladi   LCS2023032
NALLA HITHA SAI SRINATH   LCS2023001
Gana Kalvakuntla   LCS2023049
Koyyani Naga Sai Yaaghnetha   LIT2023034 
Revanth Kurapati   LIT2023024

**Comment by VinayaSathyanarayana** [comment]
Approved
