### ISSUE TITLE
[CS+IT][Team005] [Duolingo Clone]

### ISSUE THREAD

**Issue by PranavReddy0148** [IIITLucknowSWEngg/Assignment#13]
**DESCRIPTION:** Duolingo is a language-learning app that uses gamified lessons to teach over 30 languages. It offers interactive exercises to practice reading, writing, listening, and speaking skills. The platform is designed to be engaging and accessible, making language learning fun and effective.

**TEAM MEMBERS:** 

| NAME | ROLL NUMBER |
| ---- | ---- |
| Arshia Adhya | LCS2023029 |
| Anadi Mehta | LCS2023020 |
| Vinayak Chaurasia | LCS2023041 |
| Jigyasa Jamra | LIT2023014 |
| Pranav Reddy Katreddy | LIT2023004 |
| Tanishq Aswar | LIT2023029 |
| Akshita Agarwal | LIT2023056 |
| Prince Yadav | LIT2023050 |

**Comment by VinayaSathyanarayana** [comment]
Approved
