### ISSUE TITLE
[CSAI-CSB][Team - 015] [Chess.com Clone]

### ISSUE THREAD

**Issue by Radesh07** [IIITLucknowSWEngg/Assignment#14]
Project Description : 
Chess.com is an internet chess server and social networking website.The site has a freemium model in which some features are available for free, and others are available for accounts with subscriptions. Live online chess can be played against other users in daily, rapid, blitz or bullet time controls, with a number of chess variants available. Chess versus a chess engine, computer analysis, chess puzzles and teaching resources are offered.

Team Members : 

| Name | Roll Number| 
|----------|----------|
| Pranilash Reddy Pesara| LCB2023040   | 
| Annam Radesh  | LCI2023020  | 
| Sagili Nithin | LCI2023040  | 
| Yeggoni Ranadeep | LCB2023020  | 
| Devisetty Siri Maya Lalitha | LCI2023010  |

**Comment by VinayaSathyanarayana** [comment]
Approved
