### ISSUE TITLE
[CS+IT][Team009] [Blinkit Clone]

### ISSUE THREAD

**Issue by imranasumbul** [IIITLucknowSWEngg/Assignment#15]
Blinkit, formerly known as Grofers, is an instant delivery service that provides groceries and other essentials to customers within minutes. The company was acquired by Zomato in 2022, further integrating its services with Zomato's food delivery platform. 

Team Members
Nayaab Zameer (CS-36)
Mohd Haider (CS-38)
Sanyam (CS-06)
Ankit (CS-02)
Anamika Kumari (IT-36)
Saloni (IT-42)
Imrana Sumbul (IT-59)

**Comment by VinayaSathyanarayana** [comment]
Approved
