### ISSUE TITLE
[CS+IT][Team007] [Zomato Clone]

### ISSUE THREAD

**Issue by vivek23024** [IIITLucknowSWEngg/Assignment#16]
Zomato is an online food delivery and restaurant discovery platform based in India. It allows users to browse restaurant menus, read reviews, and order food for delivery or takeaway. Zomato also provides information on dining out, including ratings, photos, and details about the restaurant's ambiance, cuisine, and pricing

Team Members
Tanishk Khandelwal (it -20)
Vivek Tripathi (cs-04)
Raghvendra Mishra (cs-26)
Aaditya Raj (it-03)
Akshat Singh (cs -42)
Vaibhav Rawat (cs-33)
Jagdish Shanamwad (cs-53)
Sai Lokesh(it-57)

**Comment by VinayaSathyanarayana** [comment]
Approved
