### ISSUE TITLE
[CSAI+CSB][Team010][Decathlon Clone]

### ISSUE THREAD

**Issue by blunterdecosta123** [IIITLucknowSWEngg/Assignment#17]
Decathlon is a global retailer specializing in sports and outdoor equipment. It offers a wide range of products for various sports and activities, including clothing, footwear, and gear. Decathlon's platform allows customers to explore a diverse selection of high-quality items, read detailed product descriptions, and access expert advice on choosing the right equipment. The company is known for its commitment to affordability and innovation, making sports and fitness accessible to enthusiasts of all levels. In addition to online shopping, Decathlon also operates physical stores where customers can experience products firsthand and receive personalized assistance.

Team Members:-

PRANJAY SINGH blunterdecosta123 [singhpran15@gmail.com](mailto:singhpran15@gmail.com) LCI2023001
AKULA NAGASHIVA nagashiva00 [akulanagashiva@gmail.com](mailto:akulanagashiva@gmail.com) LCI2023041
SAMEER ANIL PAZARE youfoundmee [sameerpazare123@gmail.com](mailto:sameerpazare123@gmail.com) LCB2023056
ABINASH NAYAK abinash-30 [abinashnayakarbi30@gmail.com](mailto:abinashnayakarbi30@gmail.com) LCB2023036
SHASHANK KUMAR Shashank1913 [krshashank1399@gmail.com](mailto:krshashank1399@gmail.com) LCI2023023
RAHUL KUMAR Krahul70249 [Krahul70249@gmail.com](mailto:Krahul70249@gmail.com) LCI2023049

**Comment by VinayaSathyanarayana** [comment]
Are you doing a clone of he Mobile App or the Website?

**Comment by blunterdecosta123** [comment]
Website Clone

**Comment by blunterdecosta123** [comment]
> Are you doing a clone of he Mobile App or the Website?
Website Clone

**Comment by VinayaSathyanarayana** [comment]
Just a website may not be diverse enough... Please talk to me in the class

**Comment by VinayaSathyanarayana** [comment]
Please be present and talk to me in the class

**Comment by VinayaSathyanarayana** [comment]
Approved as overall IT System of Decathon and not just a website
