### ISSUE TITLE
[CS+IT] [TEAM010] [NETFLIX CLONE]

### ISSUE THREAD

**Issue by aditya-gg04** [IIITLucknowSWEngg/Assignment#18]
A Netflix-like Web platform is a digital content streaming service that delivers video-on-demand (VOD) to users via the internet. The platform supports the streaming of movies, TV shows, documentaries, and original content.

Team Members:

Hrushikesh Sunil Gore IT LIT2023001 

Aditya Gunjkar IT LIT2023015

Satpute Vishal Suryakant CS LCS2023052

Vedant Jadhav CS LCS2023035 

Sangale Sumit Mahadeo CS LCS2023048

Aditya Mahamuni CS LCS2023023 

Garikapati Sairam Sharan IT LIT2023009 

Soham Balwant CS LCS2023021

**Comment by VinayaSathyanarayana** [comment]
Check if there is already a team doing the same or similar

**Comment by Robinaditya1045** [comment]
> Check if there is already a team doing the same or similar

No sir, None of the teams is building project on this idea

**Comment by VinayaSathyanarayana** [comment]
Approved
