### ISSUE TITLE
[CSAI+CSB][Team012] [Google Pay Clone]

### ISSUE THREAD

**Issue by Prtm2110** [IIITLucknowSWEngg/Assignment#19]
Google Pay is a mobile app that lets users send, receive, and pay money securely. With features like bill payments, rewards, and contactless payments, it offers a simple way to manage transactions and track spending in real-time.

Pratham Hole         `LCB2023003` 
Medha Bhardwaj   `LCB2023053`
Safiya Nasir             `LCI2023053` 
Shivang Agrahari   `LCB2023030` 
Hardee Parekh       `LCB2023028`
Shresth Sharma      `LCB2023054`

**Comment by VinayaSathyanarayana** [comment]
Approved
