### ISSUE TITLE
[CS+IT][TEAM004] [Instagram Clone]

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [IIITLucknowSWEngg/Assignment#2]
Description:
This project is an Instagram Clone, a replication of the popular social media platform for sharing photos and videos. Built using Nodejs, Express , MongoDb, Socket IO and React +Vue, it aims to include the core functionalities of Instagram such as user authentication, photo sharing, liking, commenting, and following other users.
Team Members:
Om Swami (IT02)
Saloni Gupta (IT23)
Pranay Buradkar (IT27)
Aman Vishwakarma(IT32)
Karan Agarwal(IT11)

**Comment by VinayaSathyanarayana** [comment]
Approved
