### ISSUE TITLE
[ CS + IT] [ TEAM 018] [ FIT BIT APP CLONE ]

### ISSUE THREAD

**Issue by ashokkaji26** [IIITLucknowSWEngg/Assignment#20]
Fitbit is a fitness app that works with wearable devices to monitor activity, sleep, heart rate, and overall health. It allows users to set goals, track their progress, and stay motivated with workout tracking, personalized insights, and social challenges.  

Team Members - 
                             1. Karthik Batthi        LCS2023046
                             2. Ashok Kaji           LCS2023018
                             3. Suraj Kumar            LIT2023058
                             4. Pranjal Sharma         LCS2023050
                             5. Dheeraj O                LIT2023043

**Comment by VinayaSathyanarayana** [comment]
Approved. Your requests are late.
