### ISSUE TITLE
[CSAI & CSB][Team 13][ Google Docs ]

### ISSUE THREAD

**Issue by Jovial-Kanwadia** [IIITLucknowSWEngg/Assignment#21]
Google Docs is a web-based word processing tool developed by Google, allowing users to create, edit, and collaborate on documents in real-time. It supports cloud-based storage through Google Drive, ensuring easy access and sharing. With features like version history, commenting, and add-ons, it enhances productivity for individual and team work.

Team Members -
1. Aditya Masne LCI2023033
2. Naresh Sihag LCI2023043
3. Shiv Kaushik LCI2023051
4. Raunak Dange LCB2023008
5. Sparsh Sinha LCB2023005
6. Rahul Naskar LCB2023009
7. Jovial Kanwadia LCI2023047
8. Nathan Joju Thomas LCI2023015
9. Ayush Kumar LCI2023021

**Comment by VinayaSathyanarayana** [comment]
Approved. Your requests are late.
