### ISSUE TITLE
[CSAI+CSB] [Team 08] [Discord Clone]

### ISSUE THREAD

**Issue by muskan191103** [IIITLucknowSWEngg/Assignment#22]
Discord is a popular all-in-one communication platform designed for creating communities and fostering interaction through text, voice, and video. Initially popularized by gamers, Discord has evolved into a versatile tool for people with shared interests to connect, collaborate, and communicate in real time. It offers a user-friendly interface with customizable servers and channels, making it ideal for various communities, including gaming, education, businesses, and hobbyist groups.

Team Members:
Abhay Sagar CSB (LCB2023037) 
Keshav Thakur CSB (LCB2023038)
Muskan Agrawal CSAI (LCI2023030) 
Shrishti Dubey CSAI (LCI2023006)
Ayushi Awasthi CSAI (LCI2023007) 
Anurag Kumar CSAI (LCI2023036) 
Swyam Kumar CSAI (LCI2023052) 
Abhinav Sagar CSAI (LCI2023028)

**Comment by VinayaSathyanarayana** [comment]
Approved
