### ISSUE TITLE
[CSAI+CSB] [Team-007] [Youtube Clone]

### ISSUE THREAD

**Issue by 0PrashantYadav0** [IIITLucknowSWEngg/Assignment#23]
**YouTube Clone Project**

The YouTube clone project aims to replicate the core functionalities of YouTube, allowing users to upload, search, and stream videos. The project emphasizes creating a user-friendly interface and optimizing video storage, streaming, and recommendation algorithms. Through this project, the team will enhance their skills in web development, video handling, and working with databases. It offers hands-on experience with building full-stack applications and working with multimedia data.

**Team Members:**
- Prashant Kumar Yadav (CSAI, LCI2023025, GitHub ID: 0PrashantYadav0)
- Dishant Garg (CSB, LCB2023011, GitHub ID: Dishant-garg)
- Devansh Verma (CSAI, LCI2023016, GitHub ID: Invincible1602)
- Tarang Agrawal (CSAI, LCI2023013, GitHub ID: tarangagrawal6)
- Gaurav Ghodinde (CSB, LCB2023032, GitHub ID: GauravGhodinde)
- Akhand Pratap Dhiryan (CSAI, LCI2023022, GitHub ID: Akhandp10)
- Gagan Mishra (CSAI, LCI2023038, GitHub ID: GaganMishra305)
- Tanmay Janardhan Deshmukh (CSB, LCB2023011, GitHub ID: NeonKazuha)

**Comment by VinayaSathyanarayana** [comment]
Approved
