### ISSUE TITLE
[CS+IT][Team -17][Google Meet]

### ISSUE THREAD

**Issue by RISHABHKUSHWAHA7** [IIITLucknowSWEngg/Assignment#24]
Google Meet is a video conferencing tool developed by Google, designed for secure and high-quality virtual meetings. It integrates seamlessly with Google Workspace (formerly G Suite) and can be used via web browsers or mobile apps. Key features include real-time captions, screen sharing, and meeting recording.Google Meet is often used for professional meetings, educational sessions, and personal video calls, offering a user-friendly interface and reliable performance.

TEAM MEMBERS : 

Rishabh Khushwaha lit2023041 
Shubh Agarwal lit2023046 
Vishesh Singh lit2023054 
Harshit Maheswari  lit2023052 
Neelesh lit2023045
Mayank lit2023008 
Rohan Prakash lcs2023014 
Abhay Pratap Singh Ahirwar lit2023055

**Comment by VinayaSathyanarayana** [comment]
Approved
