### ISSUE TITLE
[CSAI+CSB] [Team-020] [Flipkart Clone]

### ISSUE THREAD

**Issue by Romith-27** [IIITLucknowSWEngg/Assignment#25]
Flipkart is an e-commerce platform based in India, designed to provide a seamless online shopping experience. It offers a wide range of products, including electronics, fashion, home essentials, and more. Flipkart features user-friendly navigation, secure payment options, and reliable delivery services, making it a popular choice for online shoppers. Key features include product reviews, easy returns, and personalized recommendations, catering to both individual customers and businesses.

### TEAM MEMBERS:

- Nandyala Sai Ganesh Poshith CSAI LCI2023032
- Pagadala Romith Chenna Kesav CSAI LCI2023059
- Segu Rohith Kumar CSAI LCI2023056
- Ruthvik Papabattula CSAI LCI2023017
- Sayampu Leela Aakash CSB LCB2023057
- Deevi Rahul Bharadwaz CSAI LCI2023019
- Ramcharan Teja CSB LCB2023041
- Boda Baba CSB LCB2023000

**Comment by VinayaSathyanarayana** [comment]
Approved
