### ISSUE TITLE
[CSAI+CSB][TEAM003] [ LINKEDIN CLONE ] 

### ISSUE THREAD

**Issue by shreya-2201** [IIITLucknowSWEngg/Assignment#26]
LinkedIn is a professional networking platform where users can create profiles, connect with other professionals, and explore job opportunities. Users can share posts, endorse skills, and follow companies to stay updated with industry trends. The platform also allows recruiters to post job listings and contact potential candidates.

Team Members:
Shreya Jambhale (LCI2023008)
Riya Patil (LCI2023009)
Saanvi Lohani (LCI2023005)
Diva Goyal (LCI2023014)
Nakshatra Patil (LCI2023042)
Anjali Meena (LCB2023042)
Raj Rakshit Shukla (LCB2023017)

**Comment by VinayaSathyanarayana** [comment]
Why is your submission late?

Appoved
