### ISSUE TITLE
[CS & IT][Team 020] [ OYO Clone ] 

### ISSUE THREAD

**Issue by parrth20** [IIITLucknowSWEngg/Assignment#27]
OYO is a global hospitality company offering a network of budget hotels, homes, and living spaces, providing affordable, quality accommodation for travelers. A key aspect of OYO's business is its advanced technology platform, which efficiently manages inventory, bookings, and pricing. This platform also ensures seamless communication with partner hotels, enabling real-time updates on availability, pricing, and guest feedback.

**TEAM NAME**: Innov8 Coders

**TEAM IDEA**: OYO websiteClone

**TEAM MEMBERS**:

| **Team Members**    | **Department** | **Roll Number** | **Email**                      | **GitHub Username**  |
|---------------------|----------------|-----------------|--------------------------------|----------------------|
| Abhay Prasad        | IT             | LIT2023006      | abhayprasad9494@gmail.com      | abhay9494            |
| Parth Bandwal       | IT             | LIT2023013      | parthbandwal3@gmail.com        | parrth20             |
| Satyam Gupta        | IT             | LIT2023007      | satyamgupta0812@gmail.com      | satyamgupta08        |
| Prakash Kumar       | CS             | LCS2023056      | 9101prakashkumar@gmail.com     | Prakashkumar88       |

**Comment by VinayaSathyanarayana** [comment]
Please follow the instructions on naming the issue.

**Comment by VinayaSathyanarayana** [comment]
Approved
