### ISSUE TITLE
[CSAI & CSB][Team 004]  [ Amazon Prime Video Clone ]

### ISSUE THREAD

**Issue by psg-19** [IIITLucknowSWEngg/Assignment#28]
TEAM IDEA - **Amazon Prime Video Clone**

Our platform is a global streaming service offering a diverse library of movies, TV shows, and original content, providing accessible entertainment for viewers. A key aspect of our business is the advanced technology platform, which efficiently manages content inventory, subscriptions, and streaming quality. This platform also ensures seamless communication with content providers, enabling real-time updates on availability, viewer ratings, and feedback.

Ashwini Kumar Singh: lci2023037 
Adarsh Verma: lcb2023055
Pratush Shyam Gupt: lci2023039
Veda akash yendluri vedaakash: lci2023057
Atul Gond:  lcb2023033 
Aman Choudhary:  lci2023029

**Comment by VinayaSathyanarayana** [comment]
Veda Akash to report
Atul to report

Approved.
