### ISSUE TITLE
[CSAI+CSB][Team007] [UBER Clone]

### ISSUE THREAD

**Issue by erinhdsilva** [IIITLucknowSWEngg/Assignment#3]
Description:
Uber is a mobile app that simplifies transportation by connecting riders with nearby drivers. Users can easily request rides, track their driver in real-time, and make cashless payments through the app. With features like ride scheduling, fare estimation, and driver ratings, Uber offers a seamless and convenient travel experience.

Team Members:
Erin Helga D Silva (LCB2023026)
Apoorv Mittal (LCB2023021)
Ashwin Avinash Gajbhiye (LCB2023023)
Digvijay Rahul Deshmukh (LCI2023012)
Manish Kumar (LCB2023034)
Deore Nachiket Jayant (LCB2023002)
Ujjwal Goyal (LCB2023013)
Vaibhav Verma (LCB2023029)

**Comment by VinayaSathyanarayana** [comment]
Approved
