### ISSUE TITLE
[CSAI+CSB][Team012] [E-commerce website] 

### ISSUE THREAD

**Issue by Bhargavaansh2211** [IIITLucknowSWEngg/Assignment#4]
An e-commerce website is an online platform for buying and selling goods or services. It provides a virtual storefront where customers can browse various items, view detailed product descriptions and images, and read reviews.

Team members:
Ansh Bhargava (LCB2023012)
Ajay Baghel (LCB2023004)
Akshay Kumar (LCB2023007)
Aryan Sharma (LCB2023019)
Utkarsh Gupta (LCB2023010)
Sarthak Kumar (LCI2023031)

**Comment by VinayaSathyanarayana** [comment]
Approved
