### ISSUE TITLE
[CSAI+CSB][Team011] [MYNTRA Clone]

### ISSUE THREAD

**Issue by dianasolomon** [IIITLucknowSWEngg/Assignment#5]
Myntra is a mobile app that streamlines online shopping by offering a wide range of fashion and lifestyle products at your fingertips. Users can effortlessly browse through categories, compare prices, and place orders with just a few taps. The app provides real-time updates on order status and offers convenient home delivery within a specified time frame. With features like easy returns, personalized recommendations, and secure payment options, Myntra delivers a smooth and enjoyable shopping experience.

TEAM MEMBERS:
1.  BHUMIKA WAHANE LCB2023048 
2. ANUSHKA LCB2023018 
3. KRITIKA YADAV LCB2023006 
4. DIANA SOLOMON LCB2023027 
5. SAHIN KAUSHAR LCB2023025 
6. RANJNI SINGH RAJPUT LCB2023047

**Comment by VinayaSathyanarayana** [comment]
Approved
