### ISSUE TITLE
[CS+IT][Team011] [Groww Clone]

### ISSUE THREAD

**Issue by sakshisahu27** [IIITLucknowSWEngg/Assignment#6]
Description:
Groww Clone replicates the key features of the Groww investment platform, allowing users to invest in mutual funds, stocks, and ETFs. It includes portfolio tracking, investment insights, and market analysis tools, aiming to simplify investing with a user-friendly interface similar to the original Groww platform.
Team Members:
Sakshi Sahu (IT25)
Sweta Kumari (IT19)
Ananya Varshney (IT35)
Anurag Yadav (IT21)
Mayank Mishra (CS47)

**Comment by VinayaSathyanarayana** [comment]
Approved
