### ISSUE TITLE
[CS+IT][Team008] [BookMyShow  Clone]

### ISSUE THREAD

**Issue by hitarth-gg** [IIITLucknowSWEngg/Assignment#7]
BookMyShow is an online platform for booking tickets for movies, live events, sports, and entertainment shows. It provides users with a convenient way to discover and reserve seats for various events, offering features like seat selection, show timings, and venue information. The platform is widely used for its ease of access to entertainment across different cities in India.

Team Members:

Vishal Parida : LIT2023044
Priyanshu Agarwal : LIT2023022
Piyush Kumar : LIT2023016
Hitarth Singh Rajput : LCS2023040
Aryam Agarwal : LCS2023045
Dev Darshan : LCS2023012
Satyajit Sahoo : LCS2023013
Sarthak Nayyar : LCS2023039

**Comment by VinayaSathyanarayana** [comment]
Approved
