### ISSUE TITLE
[CS+IT][Team013] [Hotstar Clone]

### ISSUE THREAD

**Issue by sanchitapatel29** [IIITLucknowSWEngg/Assignment#8]
Hotstar serves as an all-encompassing streaming platform, offering a rich array of movies, TV shows, live sports, and exclusive Disney+ content. Whether you're into Bollywood blockbusters, the excitement of live cricket, or the expansive universes of Marvel and Star Wars, Hotstar has you covered. The platform's user-friendly website and app provide instant access to top-tier entertainment, available anytime and anywhere, making it an ideal companion for all your streaming needs.

Team Members:
Amolly Choudhary : LCS2023019
Ayushi Dhete : LIT2023005 
Bhuvika Agrawal : LIT2023028 
Deepanshi Verma : LCS2023010 
Salusha : LCS2023009  
Sanchita Patel : LCS2023022 
Snehal Taori : LCS2023008

**Comment by VinayaSathyanarayana** [comment]
Approved
