### ISSUE TITLE
[CSAI-CSB][Team - 014] - [Make My Trip Clone]

### ISSUE THREAD

**Issue by Lakshya0000** [IIITLucknowSWEngg/Assignment#9]
MakeMyTrip is a popular online travel company that offers a wide range of travel services, including flight bookings, hotel reservations, holiday packages, and car rentals. It provides users with a convenient platform to plan and book their trips, offering various deals and options to suit different budgets and preferences.

Team Members:-
Lakshya Agarwal - LCI2023058
Utkarsh Srivastava-LCI2023034
Khushal - LCI2023048
Piyush Nayak - LCB2023050
Amritanshu - LCB2023046
Tanish - LCB2023045
Lavish Shakys - LCB2023035

**Comment by VinayaSathyanarayana** [comment]
Approved
